#!/usr/bin/env bash
# Configures Nginx to run as nginx user on port 8080

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80/listen [::]:8080/g' /etc/nginx/sites-available/default
id -u nginx &>/dev/null || useradd --no-create-home nginx
pkill -9 nginx 2>/dev/null || true
sleep 1
service nginx start
