#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By
apt-get update -y
apt-get install -y nginx

echo "Holberton School" | tee /var/www/html/index.html

HOSTNAME=$(hostname)
sed -i "/server_name _;/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart
