#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By
apt-get update -y
apt-get install -y nginx

echo "Holberton School" | tee /var/www/html/index.html

# Get hostname and add to nginx config
echo "add_header X-Served-By \$hostname;" > /etc/nginx/conf.d/custom_header.conf

service nginx restart
