#!/usr/bin/env bash
# Installs and configures nginx web server
apt-get update -y
apt-get install -y nginx

mkdir -p /var/www/html
echo "Holberton School" > /var/www/html/index.html

service nginx start
service nginx restart
