#!/usr/bin/env bash
# Configures nginx with a 301 redirect for /redirect_me
apt-get update -y
apt-get install -y nginx

echo "Holberton School" | tee /var/www/html/index.html

cat > /etc/nginx/sites-available/default << 'NGINX'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
NGINX

service nginx restart
