#!/usr/bin/env bash
# Configures nginx with a 301 redirect for /redirect_me
apt-get update -y
apt-get install -y nginx

echo "Holberton School" | tee /var/www/html/index.html

sed -i 's|try_files $uri $uri/ =404;|try_files $uri $uri/ =404;\n\t}\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|' /etc/nginx/sites-available/default

service nginx restart
