#!/usr/bin/env bash
# Configures nginx with a custom 404 page
apt-get update -y
apt-get install -y nginx

echo "Holberton School" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sed -i '/server_name _;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

service nginx restart
