#!/usr/bin/env bash
# Configures nginx with a custom 404 page
apt-get update -y
apt-get install -y nginx

echo "Holberton School" | tee /var/www/html/index.html

echo "Ceci n'est pas une page" | tee /var/www/html/404.html

sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default

sed -i 's|error_page 404 /404.html;|error_page 404 /404.html;|' /etc/nginx/sites-available/default
echo "error_page 404 /404.html;" >> /etc/nginx/sites-available/default

service nginx restart
